apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: resource-consumer-default
  name: resource-consumer-default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: resource-consumer-default
  template:
    metadata:
      labels:
        run: resource-consumer-default
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
        imagePullPolicy: IfNotPresent
        name: resource-consumer-default
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
         # limits:
          #  cpu: 20m
          #  memory: 64Mi
---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: resource-consumer-default
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: resource-consumer-default
    type: LoadBalancer
kind: List
